(
    MAIN_MENU,
    TONE,
    TRANSLATION,
    ANSWER,
    LANG_TO,
    MATEMATICS_MENU,
    FIRST_NUMBER,
    LAST_NUMBER,
    OPERATION,
    EQUATION_HANDLER,
    EQUATION_TEXT_RESULT,
) = range(11)