(
    MAIN_MENU,
    TONE,
    TRANSLATION,
    ANSWER,
    LANG_TO,
    MATEMATICS_MENU,
    FIRST_NUMBER,
    LAST_NUMBER,
    OPERATION,
    EQUATION_MENU,
    EQUATION_TEXT_RESULT,
    EQUATION_PHOTO_RESULT,
) = range(12)